### ISSUE TITLE
LessException with example code

### ISSUE THREAD

**Issue by frangarcia** [asual/lesscss-engine#49]
I am trying to work with this library in a Grails project but just running the example code

LessEngine engine = new LessEngine();

String text = engine.compile("div { width: 1 }");

throws the exception 

com.asual.lesscss.LessException: Syntax Error: Cannot find function trim.

The version I am working on is 1.4.2.

It seems to be working with version 1.3.3.
